spring:
  datasource:
    dynamic:
      primary: dm1
      druid:
        validation-query: SELECT 1
        initial-size: 30
        max-active: 40
        min-idle: 5
        max-wait: 60000
        pool-prepared-statements: true
        max-pool-prepared-statement-per-connection-size: 20
        validation-query-timeout: 60000
        test-on-borrow: false
        test-on-return: false
        test-while-idle: true
        time-between-eviction-runs-millis: 60000
        min-evictable-idle-time-millis: 100000
        filters: stat
        connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=1000
      datasource:
        dm1:
          #?????
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://localhost:3306/judgements?allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf-8
          username: root
          password: 123456
        dm2:
          #?????
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://localhost:3306/judgements?allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf-8
          username: root
          password: 123456
  application:
    name: sync

    # mybatis
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

date: 2022-11-23
intervalDays: 1