spring:
  data:
    mongodb:
      local:
        uri: mongodb://192.168.0.103:27017/cpws
      remote:
        #  uri: mongodb://192.168.43.188:27017/cpws
        uri: mongodb://localhost:27017/cpws

    application:
    name: sync
server:
  port: 8899
#logging:
#  level:
#    org.mongodb: debug
order: desc
pageNum: 1
